services:
  - type: web
    name: komivex
    env: python
    plan: free
    buildCommand: ""
    startCommand: python3 server.py
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /api/config
